# Generated by Django 6.0.1 on 2026-02-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchdraft',
            name='age_range',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='researchdraft',
            name='deadline',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='researchdraft',
            name='est_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchdraft',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='researchdraft',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='researchdraft',
            name='objective',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchdraft',
            name='occupations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='researchdraft',
            name='org_dept',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='researchdraft',
            name='org_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='researchdraft',
            name='org_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='researchdraft',
            name='owner_id',
            field=models.CharField(default='anonymous', max_length=100),
        ),
        migrations.AddField(
            model_name='researchdraft',
            name='question_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchdraft',
            name='sample_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='researchdraft',
            name='start_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='researchdraft',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='deadline',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='est_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='occupations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='org_dept',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='org_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='org_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='question_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='start_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('closed', 'Closed')], default='draft', max_length=20),
        ),
    ]
